M48
; DRILL file {KiCad 9.0.4} date 2026-03-12T14:42:39-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-12T14:42:39-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.270
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X161.76Y-29.571
X161.76Y-38.571
T2
X141.656Y-29.657
T3
X30.48Y-30.48
X30.48Y-40.64
X170.18Y-30.48
X170.18Y-40.64
M30
